# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Codes', path: 'menu', url: 'codes.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://zoghbi-a.github.io'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/zoghbi-a'}
- {icon: 'envelope', link: 'mailto:zoghbi.a@gmail.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Date'
